steps:
  # 1. Build Backend Container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west3-docker.pkg.dev/gcp-serverless-ecommerce/apps/medusa-backend:latest'
      - '-f'
      - 'apps/backend/Dockerfile'
      - '.'

  # 2. Build Storefront Container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west3-docker.pkg.dev/gcp-serverless-ecommerce/apps/nextjs-storefront:latest'
      - '-f'
      - 'apps/storefront/Dockerfile'
      - '.'

images:
  - 'europe-west3-docker.pkg.dev/gcp-serverless-ecommerce/apps/medusa-backend:latest'
  - 'europe-west3-docker.pkg.dev/gcp-serverless-ecommerce/apps/nextjs-storefront:latest'

options:
  machineType: 'E2_HIGHCPU_8'
