import { GenericProduct } from "@repo/types";

export const STORE_PRODUCTS: GenericProduct[] = [
  {
    id: "prod_anc_headphones_01",
    handle: "aura-pro-anc-headphones",
    title: {
      en: "Aura Pro Wireless ANC Headphones",
      de: "Aura Pro Wireless ANC Kopfhörer",
      fr: "Casque Sans Fil ANC Aura Pro",
      it: "Aura Pro Cuffie Wireless ANC",
      es: "Auriculares Inalámbricos ANC Aura Pro",
      nl: "Aura Pro Draadloze ANC Koptelefoon",
    },
    description: {
      en: "High-resolution studio audio with hybrid active noise cancellation, 40-hour battery life, and ultra-lightweight aluminum chassis.",
      de: "High-Resolution Studio-Audio mit hybrider aktiver Geräuschunterdrückung, 40h Akkulaufzeit und ultraleichter Aluminium-Konstruktion.",
      fr: "Audio haute résolution avec réduction active hybride du bruit, 40h d'autonomie et structure aluminium ultra-légère.",
      it: "Audio da studio ad alta risoluzione con cancellazione attiva del rumore ibrida, 40 ore di autonomia e telaio in alluminio ultraleggero.",
      es: "Audio de estudio de alta resolución con cancelación activa de ruido híbrida, 40 horas de autonomía y chasis de aluminio ultraligero.",
      nl: "High-resolution audio met hybride actieve ruisonderdrukking, 40 uur batterijduur en ultralichte aluminium constructie.",
    },
    brand: "Apex Direct",
    category: "Consumer Electronics",
    defaultHsCode: "8518.30.00",
    material: "Anodized Aluminum & Memory Foam",
    assemblyRequired: false,
    returnPolicyDays: 14,
    estimatedReturnCostEur: 4.90,
    media: [
      {
        id: "media_headphones_01",
        url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
        altText: "Aura Pro Wireless ANC Headphones in Midnight Black",
      },
    ],
    variants: [
      {
        id: "var_headphones_black",
        sku: "APX-AUD-PRO-BLK",
        title: "Midnight Black",
        barcode: "8680009876541",
        price: 249.0,
        originalPrice: 299.0,
        inventoryQuantity: 85,
        parcels: [
          {
            boxNumber: 1,
            boxDescription: "Retail Packaging & Travel Case",
            weightKg: 0.65,
            lengthCm: 22,
            widthCm: 18,
            heightCm: 8,
            desi: 0.63,
          },
        ],
        customs: {
          hsCode: "8518.30.00",
          countryOfOrigin: "TR",
          atrEligible: true,
          grossWeightKg: 0.65,
          netWeightKg: 0.35,
          packagesCount: 1,
        },
      },
    ],
    gpsr: {
      companyName: "EU Commerce Compliance Services GmbH",
      legalRepresentative: "Dr. Klaus Schneider",
      addressLine1: "Westhafen Tower, Speicherstraße 55",
      postalCode: "60327",
      city: "Frankfurt am Main",
      country: "Germany",
      email: "compliance@directcommerce.eu",
    },
    omnibus: {
      lowestPriceLast30Days: 249.0,
      currency: "EUR",
      validFrom: "2026-08-25T00:00:00Z",
      validTo: "2026-09-25T00:00:00Z",
    },
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-09-27T00:00:00Z",
  },
  {
    id: "prod_commuter_backpack_02",
    handle: "nordic-commuter-backpack",
    title: {
      en: "Nordic Commuter Waterproof Backpack",
      de: "Nordic Commuter Wasserfester Rucksack",
      fr: "Sac à Dos Imperméable Nordic Commuter",
      it: "Zaino Impermeabile Nordic Commuter",
      es: "Mochila Impermeable Nordic Commuter",
      nl: "Nordic Commuter Waterdichte Rugzak",
    },
    description: {
      en: "Minimalist all-weather modular backpack crafted from 100% recycled ocean-bound PET with dedicated 16-inch padded laptop sleeve.",
      de: "Minimalistischer Allwetter-Rucksack aus 100% recyceltem Ocean-Bound PET mit gepolstertem 16-Zoll Laptopfach.",
      fr: "Sac à dos tout temps minimaliste en PET 100% recyclé avec compartiment rembourré pour ordinateur 16 pouces.",
      it: "Zaino modulare all-weather realizzato in PET riciclato al 100% con scomparto imbottito dedicato per laptop da 16 pollici.",
      es: "Mochila modular para todo clima fabricada con PET 100% reciclado y compartimento acolchado para portátil de 16 pulgadas.",
      nl: "Minimalistische all-weather rugzak van 100% gerecycled PET met gewatteerd 16-inch laptopvak.",
    },
    brand: "Apex Direct",
    category: "Travel & Daily Gear",
    defaultHsCode: "4202.92.00",
    material: "100% Recycled PET & Water-Repellent TPU",
    assemblyRequired: false,
    returnPolicyDays: 14,
    estimatedReturnCostEur: 4.90,
    media: [
      {
        id: "media_backpack_01",
        url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
        altText: "Nordic Commuter Waterproof Backpack",
      },
    ],
    variants: [
      {
        id: "var_backpack_slate",
        sku: "APX-BAG-COMMUTER-SLT",
        title: "Slate Grey (24L)",
        barcode: "8680009876542",
        price: 129.0,
        originalPrice: 159.0,
        inventoryQuantity: 120,
        parcels: [
          {
            boxNumber: 1,
            boxDescription: "Shipping Parcel",
            weightKg: 1.2,
            lengthCm: 48,
            widthCm: 32,
            heightCm: 14,
            desi: 4.3,
          },
        ],
        customs: {
          hsCode: "4202.92.00",
          countryOfOrigin: "TR",
          atrEligible: true,
          grossWeightKg: 1.2,
          netWeightKg: 1.0,
          packagesCount: 1,
        },
      },
    ],
    gpsr: {
      companyName: "EU Commerce Compliance Services GmbH",
      legalRepresentative: "Dr. Klaus Schneider",
      addressLine1: "Westhafen Tower, Speicherstraße 55",
      postalCode: "60327",
      city: "Frankfurt am Main",
      country: "Germany",
      email: "compliance@directcommerce.eu",
    },
    omnibus: {
      lowestPriceLast30Days: 129.0,
      currency: "EUR",
      validFrom: "2026-08-25T00:00:00Z",
      validTo: "2026-09-25T00:00:00Z",
    },
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-09-27T00:00:00Z",
  },
  {
    id: "prod_smart_lamp_03",
    handle: "luma-minimalist-desk-lamp",
    title: {
      en: "Luma Minimalist Smart LED Desk Lamp",
      de: "Luma Minimalistische Smart LED Schreibtischlampe",
      fr: "Lampe de Bureau LED Minimaliste Luma",
      it: "Lampada da Scrivania Smart LED Minimalista Luma",
      es: "Lámpara de Escritorio LED Inteligente Minimalista Luma",
      nl: "Luma Minimalistische Smart LED Bureaulamp",
    },
    description: {
      en: "Stepless color temperature tuning, integrated 15W Qi fast wireless charging base, and glare-free precision task lighting.",
      de: "Stufenlos einstellbare Farbtemperatur, integriertes 15W Qi-Schnellladepad und blendfreie Präzisionsausleuchtung.",
      fr: "Température de couleur réglable en continu, socle de charge sans fil Qi 15W intégré et éclairage anti-éblouissant.",
      it: "Regolazione continua della temperatura colore, base di ricarica wireless rapida Qi da 15W integrata e illuminazione antiriflesso di precisione.",
      es: "Ajuste continuo de temperatura de color, base de carga inalámbrica rápida Qi de 15W integrada e iluminación de precisión antideslumbrante.",
      nl: "Traploos instelbare kleurtemperatuur, geïntegreerde 15W Qi-snellader en verblindingsvrije precisieverlichting.",
    },
    brand: "Apex Direct",
    category: "Home Office & Lighting",
    defaultHsCode: "9405.20.00",
    material: "Aviation-Grade Matte Aluminum",
    assemblyRequired: false,
    returnPolicyDays: 14,
    estimatedReturnCostEur: 4.90,
    media: [
      {
        id: "media_lamp_01",
        url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80",
        altText: "Luma Minimalist Smart LED Desk Lamp",
      },
    ],
    variants: [
      {
        id: "var_lamp_matte_black",
        sku: "APX-LGT-LUMA-BLK",
        title: "Matte Black / Qi 15W",
        barcode: "8680009876543",
        price: 89.0,
        originalPrice: 119.0,
        inventoryQuantity: 65,
        parcels: [
          {
            boxNumber: 1,
            boxDescription: "Lamp Base and Arm Assembly",
            weightKg: 1.8,
            lengthCm: 45,
            widthCm: 18,
            heightCm: 12,
            desi: 1.94,
          },
        ],
        customs: {
          hsCode: "9405.20.00",
          countryOfOrigin: "TR",
          atrEligible: true,
          grossWeightKg: 1.8,
          netWeightKg: 1.5,
          packagesCount: 1,
        },
      },
    ],
    gpsr: {
      companyName: "EU Commerce Compliance Services GmbH",
      legalRepresentative: "Dr. Klaus Schneider",
      addressLine1: "Westhafen Tower, Speicherstraße 55",
      postalCode: "60327",
      city: "Frankfurt am Main",
      country: "Germany",
      email: "compliance@directcommerce.eu",
    },
    omnibus: {
      lowestPriceLast30Days: 89.0,
      currency: "EUR",
      validFrom: "2026-08-25T00:00:00Z",
      validTo: "2026-09-25T00:00:00Z",
    },
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-09-27T00:00:00Z",
  },
  {
    id: "prod_mechanical_watch_04",
    handle: "horizon-automatic-watch",
    title: {
      en: "Horizon Minimalist Automatic Watch",
      de: "Horizon Automatikuhr Minimalist",
      fr: "Montre Automatique Minimaliste Horizon",
      it: "Orologio Automatico Minimalista Horizon",
      es: "Reloj Automático Minimalista Horizon",
      nl: "Horizon Automatisch Horloge Minimalist",
    },
    description: {
      en: "Japanese automatic movement, scratch-resistant sapphire crystal, 5 ATM water resistance, and genuine Italian leather strap.",
      de: "Japanisches Automatikuhrwerk, Saphirglas, 5 ATM wasserdicht mit echtem italienischem Lederarmband.",
      fr: "Mouvement automatique japonais, verre saphir, étanche 5 ATM avec bracelet en cuir italien véritable.",
      it: "Movimento automatico giapponese, vetro zaffiro antigraffio, resistenza all'acqua 5 ATM e cinturino in vera pelle italiana.",
      es: "Movimiento automático japonés, cristal de zafiro resistente a rayaduras, resistencia al agua de 5 ATM y correa de piel italiana genuina.",
      nl: "Japans automatisch uurwerk, saffierglas, 5 ATM waterdicht met echt Italiaans leren band.",
    },
    brand: "Apex Direct",
    category: "Watches & Accessories",
    defaultHsCode: "9102.11.00",
    material: "316L Stainless Steel & Sapphire Glass",
    assemblyRequired: false,
    returnPolicyDays: 14,
    estimatedReturnCostEur: 4.90,
    media: [
      {
        id: "media_watch_01",
        url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
        altText: "Horizon Minimalist Automatic Watch",
      },
    ],
    variants: [
      {
        id: "var_watch_silver",
        sku: "APX-WTC-HRZ-SLV",
        title: "Silver & Cognac Leather",
        barcode: "8680009876544",
        price: 199.0,
        originalPrice: 249.0,
        inventoryQuantity: 40,
        parcels: [
          {
            boxNumber: 1,
            boxDescription: "Presentation Gift Box",
            weightKg: 0.35,
            lengthCm: 16,
            widthCm: 12,
            heightCm: 8,
            desi: 0.31,
          },
        ],
        customs: {
          hsCode: "9102.11.00",
          countryOfOrigin: "TR",
          atrEligible: true,
          grossWeightKg: 0.35,
          netWeightKg: 0.15,
          packagesCount: 1,
        },
      },
    ],
    gpsr: {
      companyName: "EU Commerce Compliance Services GmbH",
      legalRepresentative: "Dr. Klaus Schneider",
      addressLine1: "Westhafen Tower, Speicherstraße 55",
      postalCode: "60327",
      city: "Frankfurt am Main",
      country: "Germany",
      email: "compliance@directcommerce.eu",
    },
    omnibus: {
      lowestPriceLast30Days: 199.0,
      currency: "EUR",
      validFrom: "2026-08-25T00:00:00Z",
      validTo: "2026-09-25T00:00:00Z",
    },
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-09-27T00:00:00Z",
  },
];

export function getProductByHandle(handle: string): GenericProduct | undefined {
  return STORE_PRODUCTS.find((p) => p.handle === handle);
}
