name: Terraform Pipeline
on:
  push:
    branches: [main, production, staging]
    paths: ["infra/terraform/**"]
  pull_request:
    branches: [main, production, staging]
    paths: ["infra/terraform/**"]
permissions:
  contents: read
  id-token: write
env:
  PROJECT_ID: gcp-serverless-ecommerce
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine Terraform Root Directory
        id: set-tf-dir
        run: |
          if [ "${{ github.ref_name }}" = "staging" ]; then
            echo "tf_root=infra/terraform/environments/staging" >> $GITHUB_OUTPUT
          else
            echo "tf_root=infra/terraform/environments/prod" >> $GITHUB_OUTPUT
          fi

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Validate Terraform Format
        run: terraform fmt -check -recursive infra/terraform

      - name: Terraform Init
        working-directory: ${{ steps.set-tf-dir.outputs.tf_root }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ steps.set-tf-dir.outputs.tf_root }}
        run: terraform validate
